name: _
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

workspace:
  - packages/canvas
  - packages/noditor
  - packages/structial

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
